apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:  # applicable at the namespace level
  limits:
  - default:  # limit
      cpu: "500m"
    defaultRequest:  # request
      cpu: "500m"
    max:
      cpu: "1"
    min:
      cpu: "100m"
    type: Container
