apiVersion: v1
kind: ResourceQuota  # applicable to an entire namespace
metadata:
  name: first-resource-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "10"
    limits.memory: "10Gi"